"""Apply operations reporting schema changes

Revision ID: 984ea6cae6ed
Revises: 57999ad510af
Create Date: 2026-07-12 15:38:49.495459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '984ea6cae6ed'
down_revision: Union[str, Sequence[str], None] = '57999ad510af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('actor_user_id', sa.UUID(), nullable=True))
    op.add_column('activity_logs', sa.Column('recipient_user_id', sa.UUID(), nullable=True))
    op.add_column('activity_logs', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.alter_column('activity_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_module'), table_name='activity_logs')
    op.drop_constraint(op.f('activity_logs_employee_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'users', ['actor_user_id'], ['id'])
    op.create_foreign_key(None, 'activity_logs', 'users', ['recipient_user_id'], ['id'])
    op.drop_column('activity_logs', 'entity_id')
    op.drop_column('activity_logs', 'employee_id')
    op.drop_column('activity_logs', 'details')
    op.drop_column('activity_logs', 'module')
    op.add_column('audit_cycles', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('audit_cycles', 'auditor_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=False)
    op.add_column('audit_findings', sa.Column('verified_by', sa.UUID(), nullable=True))
    op.add_column('audit_findings', sa.Column('status', sa.String(), nullable=False))
    op.add_column('audit_findings', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('audit_findings', 'asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('audit_findings_auditor_id_fkey'), 'audit_findings', type_='foreignkey')
    op.drop_constraint(op.f('audit_findings_asset_id_fkey'), 'audit_findings', type_='foreignkey')
    op.create_foreign_key(None, 'audit_findings', 'users', ['verified_by'], ['id'])
    op.drop_column('audit_findings', 'auditor_id')
    op.drop_column('audit_findings', 'finding')
    op.drop_constraint(op.f('resource_bookings_asset_id_fkey'), 'resource_bookings', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('resource_bookings_asset_id_fkey'), 'resource_bookings', 'assets', ['asset_id'], ['id'])
    op.add_column('audit_findings', sa.Column('finding', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_findings', sa.Column('auditor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit_findings', type_='foreignkey')
    op.create_foreign_key(op.f('audit_findings_asset_id_fkey'), 'audit_findings', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(op.f('audit_findings_auditor_id_fkey'), 'audit_findings', 'users', ['auditor_id'], ['id'])
    op.alter_column('audit_findings', 'asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('audit_findings', 'notes')
    op.drop_column('audit_findings', 'status')
    op.drop_column('audit_findings', 'verified_by')
    op.alter_column('audit_cycles', 'auditor_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=True)
    op.drop_column('audit_cycles', 'name')
    op.add_column('activity_logs', sa.Column('module', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('activity_logs', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('activity_logs', sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('activity_logs', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_employee_id_fkey'), 'activity_logs', 'users', ['employee_id'], ['id'])
    op.create_index(op.f('ix_activity_logs_module'), 'activity_logs', ['module'], unique=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.alter_column('activity_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('activity_logs', 'is_read')
    op.drop_column('activity_logs', 'recipient_user_id')
    op.drop_column('activity_logs', 'actor_user_id')
    # ### end Alembic commands ###
